name              'logrotate'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs logrotate package and provides a resource for managing logrotate configs'
version           '2.2.3'
source_url        'https://github.com/sous-chefs/logrotate'
issues_url        'https://github.com/sous-chefs/logrotate/issues'
chef_version      '>= 12.15'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
